### ISSUE TITLE
DDip -- Distributed data parallel training in notebook

### ISSUE THREAD

**Issue by philtrade** [nestordemeure/fastai-extensions-repository#1]
Hello there,

I've created [a Jupyter notebook extension `ddip`](https://www.github.com/philtrade/Ddip)  which enables distributed data parallel (DDP) training with fastai v1 *inside the interactive Jupyter notebook environment*.  Scripted, batch execution of DDP is well supported, but not for Jupyter notebooks, because the interactivity imposes constraints on keeping persistent states for the learner object, and possibly for a pool of processes.

It's a nitch extension that not many ppl maybe aware.  I am working on porting it over to v2 as well.   In case you're interested, feel free to add it to your unofficial repo.  Thanks for putting it together.

**Comment by nestordemeure** [comment]
Done :)

Happy to add it, this repo was created to give increased visibility to extensions (that tend to be quickly lost in the forum).

**Comment by philtrade** [comment]
Thank you!

Phil
